### ISSUE TITLE
My lights wont change at all

### ISSUE THREAD

**Issue by dravpin** [TakingFire/HueSaber#11]
**Describe the bug**
I drag my lights into the lights groups check all the events and click start all my light stay the way there were they dont change and nothing happens

**To Reproduce**
Steps to reproduce the behavior: connect bridge and drag lights into the lights groups check all the events and click start

**Comment by dravpin** [comment]
Solved issue on my end sorry

**Comment by TakingFire** [comment]
Glad things worked out! Let me know if you encounter anything else.

**Comment by dravpin** [comment]
I thought i has sirastatus but i didnt i swear i did before so when i saw it in requirements i went meh already have it

Other then that will chroma be supported eventually?

**Comment by TakingFire** [comment]
As much as I would love to do so, HueSaber only uses the data exposed by SiraStatus, which does not have support for Chroma. ([See here](https://github.com/denpadokei/HttpSiraStatus/issues/37))
HueSaber does have support for levels that use boost colors, though.

**Comment by dravpin** [comment]
I see thanks for explaining that i appreciate it
