### ISSUE TITLE
No lights detected

### ISSUE THREAD

**Issue by JustDaniMusic** [TakingFire/HueSaber#2]
**Describe the bug**
My house is full of lights. I have more than 60 bulbs and all that on one bridge. But the thing is i can't see my own lights. It says connected to hub and under there it says no lights detected.

**To Reproduce**
Launch the application for the first time -> Push the button on your bridge -> Connected -> No lights detected.

**Additional context**
I'm not sure if this can help you but i have more than 60+ bulbs connected to the bridge.

Image: ![NoLightsDetectHS](https://user-images.githubusercontent.com/63183257/147211141-e880177c-50df-4e06-8141-d8fc07ea1358.PNG)

**Comment by TakingFire** [comment]
There are a couple things you can look at:
- Open the console with `Ctrl+Shift+I` and send an image of any errors (red) if present, and
- Paste the following code in the console and hit Enter:
```javascript
console.log(await $.get(`http://${localStorage['bridgeIp']}/api/${localStorage['apiKey']}/lights`));
```
You *should* see a response containing all of your lights. If not, let me know what error it displays.
![A list of light data](https://i.ibb.co/84r58zQ/image.png)

*Note: as of writing, [http-status](https://github.com/opl-/beatsaber-http-status) has not been updated for 1.19, so the application will not connect to Beat Saber.*

**Comment by JustDaniMusic** [comment]
Hi there,

I've opened up a console and i've seen 1 error: 
![image](https://user-images.githubusercontent.com/63183257/147223587-1cc7a7b5-74ad-4f86-9978-f8869d361a48.png)

I'm not a program expert so i don't know if this is related to my issue but here you go anyway:

Also typing in the command you paster there above does actually show the list to all the lights in my house including the ones i want to select. Also good thing to note: Is it possible to select a hue lightstip white and color in the first place?

But it just doesn't show the lights in the applications itself.

Here is an image from what i see once i type the command: 
![image](https://user-images.githubusercontent.com/63183257/147224438-2fc6c6b9-c3a4-4ba8-8b1d-780e6ae6f9b3.png)


Thats everything i did.

**Comment by TakingFire** [comment]
I didn't account for White Temperature lights having different data (I don't own any myself), so it's causing errors.
I will release a temporary fix with the next update that simply excludes white-only lights, and see about better integration later on.
If you would send me the `state` portion of one of the lights in the list it would be much appreciated.

**Comment by JustDaniMusic** [comment]
Hi there,

I've gone ahead and make a screenshot for you. This is all the information that was in the state portion.
If you need more information let me know.

Screenshot:
![image](https://user-images.githubusercontent.com/63183257/147320238-0e84ed46-77cd-431b-9fcd-ae4a28a79da5.png)

**Comment by TakingFire** [comment]
The 'No Lights Detected' issue should be fixed in the [latest release](https://github.com/TakingFire/HueSaber/releases/v1.1.0), following 03c7c6fc992e75700c1a3a2208a2bd1e61ae02ff.
I've also added better support for a large number of lights, though keep in mind the Bridge only supports streaming to 10 lights (the ones in light groups) at a time.
Please let me know if you experience any more issues with your non-color lights!
