### ISSUE TITLE
Chroma Support / Automatic Base Colors

### ISSUE THREAD

**Issue by JustDaniMusic** [TakingFire/HueSaber#5]
**Describe your request**
Add support for the plugin: Chroma so that it supports multiple colors witch will be changed automatically depending on the colours in the map events and maybe even detect custom enviroment enchantments from chroma. And maybe add a feature that it syncs the base colours with the colours in the game.

**Additional context**
(I don't have any)

**Comment by TakingFire** [comment]
HueSaber isn't a mod, think of it as a middleman between Beat Saber and your lights. I only use the data provided by [http-status](https://github.com/opl-/beatsaber-http-status), which does not support Chroma (and was not built to do so).
An option to automatically get the base colors (and boost colors) for each stage is something I can do, however. It's on the list of things to add, and I'll close this when I eventually do so.
Cheers 🙂

**Comment by TakingFire** [comment]
Automatic beatmap colors have been added in the latest release, following d5ea37f.
You can enable them via the button in the top left of the `Base Colors` panel.
