### ISSUE TITLE
Wont connect to bridge

### ISSUE THREAD

**Issue by Jaitie018** [TakingFire/HueSaber#9]
I pressed the button on the bridge but it wont connect
The program just stays blurred and im unable to click on anything other than the refresh lights button and exit button

**Comment by TakingFire** [comment]
If you open the console with `Ctrl+Shift+I`, what do you see?
You should see a message similar to "_Bridge found at 192.168.0.x, waiting for button..._".
You should also see the same IP address if you visit [this link](https://discovery.meethue.com/).
If not, a bridge couldn't be detected for some reason.

**Comment by Jaitie018** [comment]
It just randomly started working
